// Seed data for the static demo build (see demoApi.js). Timestamps are
// relative to load time so the demo always looks "fresh".
const now = Date.now();
const hours = (n) => n * 60 * 60 * 1000;
const days = (n) => n * 24 * 60 * 60 * 1000;

// 1x1 transparent PNG — stands in for a real screenshot attachment.
const PIXEL_PNG_BASE64 =
  'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=';

const CRASH_LOG = `Fatal Exception: NSInvalidArgumentException
0   CoreFoundation   0x00000001a1b1c2d0 __exceptionPreprocess
1   Sluice           0x0000000104f2a110 -[SyncEngine flush] + 212
2   Sluice           0x0000000104f2a3c4 -[SyncEngine scheduleFlush] + 88
3   libdispatch.dylib 0x00000001a0d3f120 _dispatch_call_block_and_release
`;

export function makeDemoReports() {
  return [
    {
      id: 'a1b2c3d4-0001-4000-8000-000000000001',
      created: now - hours(2),
      category: 'crash',
      summary: 'App crashes on launch after update',
      description:
        'Opened the app right after updating to 1.4.2 and it crashed immediately on the splash screen. Happens every time, on both my phone and tablet.',
      email: 'ana@example.com',
      installation_id: 'inst-7f3a9c',
      app_version: '1.4.2',
      os_version: 'iOS 17.5',
      metadata: JSON.stringify({ locale: 'en-US', build: '1.4.2 (884)' }, null, 0),
      status: 'new',
      github_url: null,
      attachments: [
        {
          id: 'b1000000-0000-4000-8000-000000000001',
          name: 'crash.log',
          content_type: 'text/plain',
          created: now - hours(2),
          content: { text: CRASH_LOG },
        },
      ],
    },
    {
      id: 'a1b2c3d4-0002-4000-8000-000000000002',
      created: now - hours(6),
      category: 'bug',
      summary: 'Attachments fail to upload over 10MB',
      description:
        'When attaching a screen recording larger than ~10MB the upload spinner never finishes and the report never gets submitted.',
      email: 'devon@example.com',
      installation_id: 'inst-2b88d1',
      app_version: '1.4.1',
      os_version: 'Android 14',
      metadata: JSON.stringify({ locale: 'en-GB', network: 'wifi' }, null, 0),
      status: 'new',
      github_url: null,
      attachments: [],
    },
    {
      id: 'a1b2c3d4-0003-4000-8000-000000000003',
      created: now - hours(20),
      category: 'feature',
      summary: 'Add keyboard shortcuts for triage actions',
      description:
        'Would love a shortcut to archive/promote/mark-spam the currently open report without reaching for the mouse each time.',
      email: 'priya@example.com',
      installation_id: 'inst-99aa01',
      app_version: '1.4.2',
      os_version: 'macOS 14.5',
      metadata: JSON.stringify({ locale: 'en-US' }, null, 0),
      status: 'new',
      github_url: null,
      attachments: [
        {
          id: 'b1000000-0000-4000-8000-000000000002',
          name: 'mock-shortcuts.png',
          content_type: 'image/png',
          created: now - hours(20),
          content: { base64: PIXEL_PNG_BASE64 },
        },
      ],
    },
    {
      id: 'a1b2c3d4-0004-4000-8000-000000000004',
      created: now - days(1),
      category: 'other',
      summary: 'Question about data retention policy',
      description:
        'Not a bug — just wondering how long submitted reports and their attachments are retained for.',
      email: 'sam@example.com',
      installation_id: 'inst-44cd77',
      app_version: '1.4.0',
      os_version: 'Windows 11',
      metadata: JSON.stringify({ locale: 'en-US' }, null, 0),
      status: 'new',
      github_url: null,
      attachments: [],
    },
    {
      id: 'a1b2c3d4-0005-4000-8000-000000000005',
      created: now - days(2),
      category: 'bug',
      summary: 'Dark mode toggle resets on every launch',
      description:
        'I switch to dark mode, close the app, and it is back to light mode the next time I open it.',
      email: 'jonas@example.com',
      installation_id: 'inst-11ff22',
      app_version: '1.3.9',
      os_version: 'iOS 17.4',
      metadata: JSON.stringify({ locale: 'de-DE' }, null, 0),
      status: 'promoted',
      github_url: 'https://github.com/demo-org/demo-app/issues/482',
      attachments: [],
    },
    {
      id: 'a1b2c3d4-0006-4000-8000-000000000006',
      created: now - days(3),
      category: 'crash',
      summary: 'Random freeze when scrolling long lists',
      description:
        'The app freezes for a few seconds every time I scroll quickly through a list with 200+ items, then recovers.',
      email: 'lee@example.com',
      installation_id: 'inst-33aa88',
      app_version: '1.3.8',
      os_version: 'Android 13',
      metadata: JSON.stringify({ locale: 'en-US' }, null, 0),
      status: 'promoted',
      github_url: 'https://github.com/demo-org/demo-app/issues/470',
      attachments: [],
    },
    {
      id: 'a1b2c3d4-0007-4000-8000-000000000007',
      created: now - days(4),
      category: 'other',
      summary: 'buy cheap watches at my store!!',
      description: 'visit best-watches-online.example for deals',
      email: 'totally-real@example.com',
      installation_id: 'inst-00spam',
      app_version: '1.0.0',
      os_version: 'unknown',
      metadata: JSON.stringify({}, null, 0),
      status: 'spam',
      github_url: null,
      attachments: [],
    },
    {
      id: 'a1b2c3d4-0008-4000-8000-000000000008',
      created: now - days(5),
      category: 'other',
      summary: 'asdkjaslkdj test test 123',
      description: 'test',
      email: 'test@test.test',
      installation_id: 'inst-00test',
      app_version: '0.0.1',
      os_version: 'unknown',
      metadata: JSON.stringify({}, null, 0),
      status: 'spam',
      github_url: null,
      attachments: [],
    },
    {
      id: 'a1b2c3d4-0009-4000-8000-000000000009',
      created: now - days(10),
      category: 'feature',
      summary: 'Export triage history to CSV',
      description:
        'Filed a while back — would still be nice to have, but not urgent given the current export scripts.',
      email: 'priya@example.com',
      installation_id: 'inst-99aa01',
      app_version: '1.2.0',
      os_version: 'macOS 14.2',
      metadata: JSON.stringify({ locale: 'en-US' }, null, 0),
      status: 'archived',
      github_url: null,
      attachments: [],
    },
    {
      id: 'a1b2c3d4-0010-4000-8000-000000000010',
      created: now - days(14),
      category: 'bug',
      summary: 'Typo in onboarding screen',
      description: 'Second onboarding screen says "recieve" instead of "receive". Fixed in the next release.',
      email: 'ana@example.com',
      installation_id: 'inst-7f3a9c',
      app_version: '1.1.0',
      os_version: 'iOS 16.6',
      metadata: JSON.stringify({ locale: 'en-US' }, null, 0),
      status: 'archived',
      github_url: null,
      attachments: [],
    },
    {
      id: 'a1b2c3d4-0011-4000-8000-000000000011',
      created: now - hours(1),
      category: 'crash',
      summary: 'Crash when rotating device during upload',
      description:
        'Rotating from portrait to landscape mid-upload force-closes the app. Reproduced 4/5 times on the same device.',
      email: 'mika@example.com',
      installation_id: 'inst-55bb90',
      app_version: '1.4.2',
      os_version: 'Android 15',
      metadata: JSON.stringify({ locale: 'ja-JP' }, null, 0),
      status: 'new',
      github_url: null,
      attachments: [],
    },
    {
      id: 'a1b2c3d4-0012-4000-8000-000000000012',
      created: now - days(6),
      category: 'feature',
      summary: 'Support pasting images directly into report description',
      description:
        'Right now I have to save a screenshot then attach it. Pasting from clipboard would save a few steps.',
      email: 'devon@example.com',
      installation_id: 'inst-2b88d1',
      app_version: '1.3.7',
      os_version: 'Android 14',
      metadata: JSON.stringify({ locale: 'en-GB' }, null, 0),
      status: 'promoted',
      github_url: 'https://github.com/demo-org/demo-app/issues/455',
      attachments: [],
    },
    {
      id: 'a1b2c3d4-0013-4000-8000-000000000013',
      created: now - days(8),
      category: 'other',
      summary: 'FREE GIFT CARD CLICK HERE',
      description: 'claim your prize now at totally-legit-prizes.example',
      email: 'winner@example.com',
      installation_id: 'inst-00spam2',
      app_version: '1.0.0',
      os_version: 'unknown',
      metadata: JSON.stringify({}, null, 0),
      status: 'spam',
      github_url: null,
      attachments: [],
    },
    {
      id: 'a1b2c3d4-0014-4000-8000-000000000014',
      created: now - days(21),
      category: 'bug',
      summary: 'Push notifications arrive twice',
      description:
        'Every notification for a new triage assignment shows up as two identical banners a second apart.',
      email: 'lee@example.com',
      installation_id: 'inst-33aa88',
      app_version: '1.2.4',
      os_version: 'Android 13',
      metadata: JSON.stringify({ locale: 'en-US' }, null, 0),
      status: 'archived',
      github_url: null,
      attachments: [],
    },
  ];
}
